### ISSUE TITLE
npx react-native init run per instructions does not seem to work

### ISSUE THREAD

**Issue by adamsythe** [invertase/react-native-firebase-authentication-example#4] opened 2021-11-29 14:55 UTC
Hi there, this temlate looks really interesting however I am unable to install it

I ran 
sudo npx react-native init ProjectName --template invertase/react-native-firebase-authentication-example

But it errors with

✖ Downloading template
error Error: Command failed: npm install --save --save-exact invertase/react-native-firebase-authentication-example
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /Users/user/.npm/_cacache/tmp/git-clonePIonBs/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/Users/user/.npm/_cacache/tmp/git-clonePIonBs/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

I tried using other templates and that seems to work, not exactly sure whats going on here.  

PS i understand this project wont get much support but just trying my luck :)

**Comment by mikehardy** [comment] 2021-11-29 15:15
1) :warning:  OMG SUDO! :warning: Why sudo, do not do these things as sudo, that literally gives me the shivers. https://search.brave.com/search?q=npm+supply+chain+attacks
2) That's a problem on your local machine with npm having a hiccup of some sort. Did it still not work even if you retried? I was re-init'ing it a ton yesterday while working on it.

It may end up getting more unofficial-at-least support then expected at first, as I decided to go all in on it to make it actually do all the things I need in a group of work apps, and now my work apps are based on it, so I'm going to be here a lot ;-)

It really should work

**Comment by mikehardy** [comment] 2021-11-29 15:16
Oh wait, I have a hunch - I was re-initing but from local directory, and npm didn't need the package.json in the root for that. There is no package.json in the root currentyl. Quick fix.

**Comment by mikehardy** [comment] 2021-11-29 15:22
Should work now? Would love to hear if it works for you - the init at least

**Comment by adamsythe** [comment] 2021-11-29 15:28
@mikehardy  that seems to have fixed the problem however its throwing a new error now, not sure if i should create new thread?

✖ Copying template
error Error: Couldn't find the "/var/folders/s6/_xyrkp595_g829865k1_b3qh0000gn/T/rncli-init-template-9M8Msi/node_modules/invertase/react-native-firebase-authentication-example/template.config.js file inside "invertase/react-native-firebase-authentication-example" template. Please make sure the template is valid. Read more: https://github.com/react-native-community/cli/blob/master/docs/init.md#creating-custom-template

**Comment by mikehardy** [comment] 2021-11-29 15:33
Well, that one I just don't understand :thinking: 

It's there... https://github.com/invertase/react-native-firebase-authentication-example/blob/main/template.config.js

This should not be the required method, but I wonder what would happen if you clone it to local disk then init using the relative path to the folder?

**Comment by adamsythe** [comment] 2021-11-29 15:37
thanks ill take a look may only be able to get back to you this evening.  Thanks again for your work on this, its hopefully just what i need for a project f mine :)

**Comment by adamsythe** [comment] 2021-11-29 15:38
i have it cloned, how do i init using relative path to finder?  So i am in root of this project then what command would i write?

**Comment by mikehardy** [comment] 2021-11-29 15:42
You need to be in a directory where you are happy to make a new project as a sub-directory.
Then if you cloned it to `<dir>/react-native-firebase-auth-example` you would run:
`npx react-native init <MyAwesomeProject> --template <dir>/react-native-firebase-auth-example`

The result of that will be a sub-directory MyAwesomeProject, all set up to go (ideally)

If you do it with the specific project name "ProjectName", you'll be able to test things out of the box. That's only interesting to look
If you do it with anything besides "ProjectName" (which is the way you'll use it for real if not just looking) then you have all the config to do with firebase before it's ready

Both should *run* though at least.

**Comment by adamsythe** [comment] 2021-11-29 15:49
im in a folder called projects that has this clone in it.  I want to build a project called wcms

I ran this command

npx react-native init wcms --template react-native-firebase-auth-example

and got a 404

**Comment by adamsythe** [comment] 2021-11-29 15:50
i tried 
npx react-native init wcms --template ./react-native-firebase-auth-example
and got

error Error: Command failed: npm install --save --save-exact ./react-native-firebase-auth-example
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /private/var/folders/s6/_xyrkp595_g829865k1_b3qh0000gn/T/rncli-init-template-yJ5x5p/react-native-firebase-auth-example/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/private/var/folders/s6/_xyrkp595_g829865k1_b3qh0000gn/T/rncli-init-template-yJ5x5p/react-native-firebase-auth-example/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by mikehardy** [comment] 2021-11-29 15:57
that looks seriously wrong, in your local environment, perhaps related to the sudo usage prior but I'm really not sure.
I just ran it clean on a machine that hasn't touched this template or anything related to it yet
Perhaps you have "react-native" installed globally and it's outdated? I do not, if I run "npm -g list --depth=0" I literally have just npm and yarn installed ?

```
mike@Bendy:~ % cd work/react-random/
mike@Bendy:~/work/react-random % npx react-native init RNFBAuthExTest --template invertase/react-native-firebase-authentication-example
npx: installed 637 in 107.046s
                                                          
               ######                ######               
             ###     ####        ####     ###             
            ##          ###    ###          ##            
            ##             ####             ##            
            ##             ####             ##            
            ##           ##    ##           ##            
            ##         ###      ###         ##            
             ##  ########################  ##             
          ######    ###            ###    ######          
      ###     ##    ##              ##    ##     ###      
   ###         ## ###      ####      ### ##         ###   
  ##           ####      ########      ####           ##  
 ##             ###     ##########     ###             ## 
  ##           ####      ########      ####           ##  
   ###         ## ###      ####      ### ##         ###   
      ###     ##    ##              ##    ##     ###      
          ######    ###            ###    ######          
             ##  ########################  ##             
            ##         ###      ###         ##            
            ##           ##    ##           ##            
            ##             ####             ##            
            ##             ####             ##            
            ##          ###    ###          ##            
             ###     ####        ####     ###             
               ######                ######               
                                                          

                  Welcome to React Native!                
                 Learn once, write anywhere               

✔ Downloading template
✔ Copying template
✔ Processing template
⠦
```

```
mike@bistromath:~ % npm -g list --depth=0
/home/mike/.nvm/versions/node/v14.18.1/lib
├── npm@6.14.15
└── yarn@1.22.17
```

outdated things in global npm modules are such a common source of error that I never install anything there on purpose

**Comment by adamsythe** [comment] 2021-11-29 15:59
mine gives this

├── appcenter-cli@2.10.0
├── expo-cli@4.13.0
└── npm@8.1.4

Do i need yarn?  Maybe that's my problem

**Comment by mikehardy** [comment] 2021-11-29 16:04
No, yarn is optional. Should work with out it, it's just so much faster I never use npm.
I fear something about one of those, I'm just not sure. All I can say for sure is that on a clean machine I cannot reproduce, it worked for me as expected from the doc. 

On the plus side, now that you have it cloned, you can actually just go right into the template directory and try to use it. It will of course be set up as "ProjectName" but it's a live app sitting in that template. That will at least give you an indication whether it is useful enough for you to continue fuzz-busting whatever the heck is causing it to work for me but not for you

**Comment by criszz77** [comment] 2021-11-29 17:30
It seems to be working for me. Try these: 

> This template only works with the new CLI. Please make sure that: 
> - [your environment is set up correctly for React Native CLI.](https://reactnative.dev/docs/environment-setup)
> - you have uninstalled the legacy `react-native-cli` first (`npm uninstall -g react-native-cli`) for the below command to work. If you wish to not use npx, you can also install the new CLI globally (`npm i -g @react-native-community/cli` or `yarn global add @react-native-community/cli`).

> If you tried the above and still get the invertase/react-native-firebase-authentification-example: Not found error, please try adding the `--ignore-existing` flag to force npx to ignore any locally installed versions of the CLI and use the latest.
Further information can be found here: https://github.com/react-native-community/cli#about

**Comment by mikehardy** [comment] 2021-12-02 18:18
Since we can't reproduce this, I'm going to close it. We're obviously interested in it working though, if we can reproduce we can reopen

**Closed by mikehardy** 2021-12-02 18:18 UTC
